# Generated by Django 5.0.3 on 2024-03-13 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('summer', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('autumn', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('spring', models.CharField(blank=True, default='', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('fam', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('otc', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('other_title', models.CharField(blank=True, max_length=128, null=True)),
                ('connect', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('add_time', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('NW', 'new'), ('PN', 'pending'), ('AC', 'accepted'), ('RJ', 'rejected')], default='NW', max_length=2)),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.coords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.users')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=128)),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='perevals.pereval')),
            ],
        ),
    ]
