version: "3.9"

services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
#      - postgres_data:/var/lib/postgresql/data/
      - ./code/:/var/lib/postgresql/data/

    ports:
      - ${PORTS}
    restart: unless-stopped

#volumes:
#  postgres_data: